### ISSUE TITLE
[DR] Link

### ISSUE THREAD

**Issue by Cl0v1s** [Cl0v1s/Canaille#11]
Dr du link prête !

**Comment by Dehelssey** [comment]
Une ptite transition ? genre `all .4s ease` ?

Sinon ça le fait.

T'as vu que quand c'est un lien externe y'a une ptite flèche vers le coin supérieur droit qui apparait ?

**Comment by Cl0v1s** [comment]
Ca marche j'ajoute la transition !
Pour ce qui est icône, ça s'ajoutera à l'usage, le DS ne peut pas savoir quand le lien est externe ou pas :)

--

**Comment by Dehelssey** [comment]
après oui au niveau de la prez dans le DS je sais pas comment ça marche en back de ton côté, au pire tu peux feinter avec une classe pour présenter les deux types de liens quoi...

**Comment by Cl0v1s** [comment]
C'est plutôt à l'appel que je comptais les mettre, j'utilise rarement des liens relatifs

**Comment by Cl0v1s** [comment]
Transition ajoutée

**Comment by Dehelssey** [comment]
je vais faire mon chieur, mais en fait je viens de tilter que sur Figma j'avais pas pu faire ce que je voulais : changer la couleur du soulignement (c'est natif CSS mais pas Figma -_-)

après j'ai peur que le soulignement soit pas assez visible si c'est vert sur fond sable là donc j'hésite.

allez, restons sobre, je valide comme ça !
