### ISSUE TITLE
[DR] SmallIInput

### ISSUE THREAD

**Issue by Cl0v1s** [Cl0v1s/Canaille#7]
SmallInput disponible !

**Comment by Dehelssey** [comment]
arf j'avais pas pensé qu'il faudrait une bordure transparente sur les 3 autres bords... Du coup ça crée un biseau sur la bordure bottom :(

En même temps si on fait pas ça on a l'input qui se réduit un peu avec l'apparition des bordures.

Bon ben go, je chipote!^^
