### ISSUE TITLE
[DR] Line

### ISSUE THREAD

**Issue by Cl0v1s** [Cl0v1s/Canaille#9]
DR du composant Line prête

**Comment by Dehelssey** [comment]
ah je pensais traiter ça avec des border lol.

border-left et border-right sur le fil central.
border-bottom sur chaque post
border-bottom sur les sections nécessaires des colonnes latérales.

Mais effectivement ça peut aussi être une line entre chaque post et une line entre chaque section des colonnes.

RAS en tout cas :)

**Comment by Cl0v1s** [comment]
Il n'est pas possible (ou du moins compliqué) de faire des borders pointillées comme tu le souhaites. C'est normalement à la main du navigateur et non-paramétrable, l'astuce consiste à utiliser un background-image, auquel cas la couleur n'est pas paramétrables à la volée.

Comme ça on a le meilleur des deux mondes :)

--

**Comment by Dehelssey** [comment]
`border: 2px dashed black;` et bim. 🤔

**Comment by Cl0v1s** [comment]
Oui, mais elle ne serait pas 4px 4px comme demandé :)
L'espacement et la taille des lignes est géré par le navigateur, donc ça dépend de ton navigateur le rendu final

--

**Comment by Dehelssey** [comment]
ah ouais my bad j'avais pas tilté que j'avais défini une longueur et un gap précis...

et Figma qui propose comme code : border: 2px solid var(--dark) balec des tirets^^

bon ben go SVG alors \o/

**Comment by Cl0v1s** [comment]
Si c'est bon pour toi, hésite pas à fermer le ticket ! :)

--
